### PR TITLE
Port to official LitElement

### PR DESCRIPTION
**Pull request by filipbech**
This is basically just a test of how a port to the real LitElement of a bigger project could be... the module-resolution stuff is a bitch - because lit-element and lit-html no longer ships functioning javascript in the bundle (I dont understand why this is the case). 
I build (and committed) some files into this PR, but for ease of use (and further updates) I think we should switch to a hosted version using unpkg... like this instead... (or go all typescript and include a simple build setup)

´´´ts
import { html, LitElement } from 'https://unpkg.com/@polymer/lit-element@latest/lit-element.js?module';
import { repeat } from 'https://unpkg.com/lit-html@0.13.0/directives/repeat.js?module';
```

Also... I haven't testet the bluetooth stuff as I haven't really changed anything there, but stuff renders to the page without runtime errors now (my bluetooth device is at work)... 

What do you think @larsgk ?

### CODE REVIEW

**Comment by kenchris** [comment]
Why not ask @justinfagnani ?

**Comment by kenchris** [comment]
btw, do you really need to use repeat? ie. are you reordering existing nodes?

**Comment by filipbech** [comment]
I agree that repeat is probably not needed, but I tried to keep the port as minimal as possible...

**Comment by larsgk** [comment]
Thanks a lot :) - I'm gonna make you and @kenchris co-owners of the repos

**Comment by filipbech** [comment]
Thanks. But how do you feel about moving the modules på unpkg? its an external dependency but it makes everything easier in our end..?

**Comment by larsgk** [comment]
Sounds good to me :) these repos were mostly done for smaller workshops
(kept fairly simple).

**Comment by justinfagnani** [comment]
Many tools support re-writing bare module specifiers to URLs - Polymer tools, unpkg, WebPack, Rollup Parcel... We use them because there's really no other way to do it. With npm we do not know where dependencies will be installed relative to our package.

re unpkg.com, it's great to serve demos and samples from, but I wouldn't ever hard-code unpkg URLs into a package. It forces unpkg on transitive dependants and users.

**Pull request merged**
